# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='banner',
            field=models.FileField(blank=True, upload_to=b'images/productimages'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, upload_to=b'images/banner'),
        ),
    ]
